---
title: "01-Plots_and_statistics"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

ID: "AD" \~ "FP1" "MB" \~ "FP2" "MM" \~ "FP3" "MS" \~ "FP4" "NL" \~ "FP5"

```{r}
library(tidyverse)
#ggthemr::ggthemr("greyscale")
#Main objective with this chunk is to import the original modelled data from anybody (metabolicModels) 
#and the data from the python script that went through the pulmonary gas exchange data (metabolicEquation)
#then merging them.


#We are mainly interested in the "anymet" column from this csv
metabolicModels <- read_csv("metabolisme_data.csv") %>% 
  mutate(
    subjects = case_when(
      subjects ==  "AD" ~ "FP1",
      subjects ==  "MB" ~ "FP2",
      subjects ==  "MM" ~ "FP3",
      subjects ==  "MS" ~ "FP4",
      subjects ==  "NL" ~ "FP5"),
    
    intensity = substr(intensity, 1,2),
    ID = paste(subjects, contraction, intensity, sep="_")
  )

#All the data from the python script.
path = "../data/vynProcessedData/"
dataList <- list.files(path = path, pattern = ".csv", full.names = TRUE) %>% 
  map(~data.table::fread(.))

metabolicEquation <- dataList %>% 
  bind_rows(dataList) %>%    # make larger sample data
  mutate_if(is.list, simplify_all) %>%    # flatten each list element internally 
  unnest() %>% 
  mutate(
    Contraction = case_when(
      Contraction == "con" ~ "Concentric",
      Contraction == "exc" ~ "Eccentric"),
    ID = paste(Subject, Contraction, Load, sep="_")
  )

#merge them so we have the output from the muscuskeletal model with the gas exchange + other information
df <- merge(metabolicModels, 
            metabolicEquation,
            by = "ID") %>% 
  select(ID, AnyMet, model, MetabolicWorkPerRep, MetabolicCalculation, Ekstension_time, 
         Flexion_time, Work.y, Watt, Subject, Load, Contraction, Bw) %>% 
  rename(work = Work.y,
         modelled_work_per_rep = AnyMet) %>% 
  janitor::clean_names() %>% 
  mutate(
    mech_watt_kg = (watt / bw),
    modelled_watt_kg= (modelled_work_per_rep /  (`ekstension_time` + `flexion_time`)) / bw,
    metabolic_watt_kg = (metabolic_work_per_rep /  (`ekstension_time` + `flexion_time`)) / bw
  ) %>% 
  distinct()

data.table::fwrite(df, "cleaned_metabolisme_data.csv")
```


```{r}
#Main plot
koeligvinPlot <- function(metabolicCalculation){
  p1 <- df %>% 
    filter(model != "Bhargava_on" & model != "Margaria1" & model != "ModifiedMargaria") %>%
    filter(metabolic_calculation == metabolicCalculation) %>% 
    mutate(modelConType = as_factor(paste(model, contraction, sep=" ")),
           modelConType = factor(modelConType, 
                                 levels = c("Margaria Concentric", 
                                            "Margaria Eccentric", 
                                            "Bhargava Concentric",
                                            "Bhargava Eccentric",
                                            "Umberger Concentric",
                                            "Umberger Eccentric"))) %>% 
    ggplot(aes(x = metabolic_watt_kg, y = modelled_watt_kg, color = subject)) + 
    geom_point(alpha = .5) + 
    stat_smooth(method = "lm", formula = y ~ x, se = FALSE, alpha=.5, lwd = .5) + 
    stat_smooth(aes(group = model), method = "lm", formula = y ~ x, se = FALSE, color = "black", lwd = 1.25) +
    geom_abline(intercept = 0, slope = 1, linetype = "dashed") +
    xlim(0,2.75) + 
    ylim(0,2.75) + 
    facet_wrap(~modelConType, ncol = 2,
               labeller = label_wrap_gen(width=10)) + 
    labs(
      x = "Calculated [watt / kg]",
      y = "Measured [watt / kg]"
    ) + 
    theme_minimal() + 
    theme(
      aspect.ratio = 0.75,
      strip.text.x = element_text(
        size = 15, face = "bold"),
      axis.title = element_text(
        size = 15, face="bold"),
      legend.position = "none",
      axis.text.x = element_text(size = 18),
      axis.text.y = element_text(size= 18),
      plot.title = element_text(size = 25, face = "bold")
    )
  
  return(p1)
}

p1 <- koeligvinPlot("original_peronnet")
p1

ggsave(file="../resultater/KoeleWijnPlotSecondRun.jpeg", plot = p1, width=10, height=8, dpi = 1200)
```


### Linear model

```{r}
#Picking the calculation for oxygen to energy we want: Peronnets original work
#Then removing the 3 models we are not interested in.
df_peronnet <- df %>% 
  filter(metabolic_calculation == "original_peronnet", 
         !model %in% c("Bhargava_on", "Margaria1", "ModifiedMargaria"))

#Two functions broom::tidy() and broom::glance() are used to get different metrics out.

#Calculating the coefficients of a linear model for the metabolic models relative to the mechanical watt
AnyMet_lm_tidy <- df_peronnet %>% 
  group_by(model, contraction) %>% 
  do(broom::tidy(lm(modelled_watt_kg ~ mech_watt_kg, .)))

#Calculating the coefficients of a linear model for the measured energy relative to the mechanical watt
VynMet_lm_tidy <- df_peronnet %>% 
  group_by(contraction) %>% 
  do(broom::tidy(lm(metabolic_watt_kg ~ mech_watt_kg, .))) %>% 
  mutate(model = "original_peronnet", .before = "contraction")

lm_tidy <- bind_rows(AnyMet_lm_tidy, VynMet_lm_tidy)

#Calculating the coefficients of a linear model for the metabolic models relative to the mechanical watt
AnyMet_lm_glance <- df_peronnet %>% 
  group_by(model, contraction) %>% 
  do(broom::glance(lm(modelled_watt_kg ~ mech_watt_kg, .)))

#Calculating the coefficients of a linear model for the measured energy relative to the mechanical watt
VynMet_lm_glance <- df_peronnet %>% 
  group_by(contraction) %>%
  do(broom::glance(lm(metabolic_watt_kg ~ mech_watt_kg, .))) %>% 
  mutate(model = "original_peronnet", .before = "contraction")

lm_glance <- bind_rows(AnyMet_lm_glance, VynMet_lm_glance) %>% 
  select(model, contraction, r.squared, adj.r.squared, p.value)

lmInfo <- merge(lm_tidy, lm_glance, by = c("model","contraction"))

```

```{r}
#Calculating mean absolute error and root mean square error relative to the metabolic model
#and contraction type
AnymetError <- df_peronnet %>% 
  group_by(model, contraction) %>% 
  mutate(mae = mean(abs(modelled_watt_kg - metabolic_watt_kg)),
         rmse = mean((modelled_watt_kg - metabolic_watt_kg)^2),
         .after = "id") %>% 
  ungroup() %>% 
  select(mae, rmse, contraction, model) %>% 
  distinct()

```

```{r}
#Plotting the absolute difference in J for the mean representative leg extension
df_peronnet %>%
  mutate(moveID = paste(contraction, load, model, sep="_")) %>% 
  group_by(moveID) %>% 
  mutate(modMean = mean(modelled_work_per_rep/bw),
         modsd = sd(modelled_work_per_rep/bw),
         metMean = mean(metabolic_work_per_rep/bw),
         metsd = sd(metabolic_work_per_rep/bw)) %>% 
  ungroup() %>% 
  ggplot(aes(x = load, y = modMean)) + 
  geom_line(size = 2.5, alpha = 0.5, color = "#a9a9a9") + 
  geom_point(size = 7) + 
  geom_errorbar(aes(ymin = modMean-modsd, ymax = modMean + modsd), width = 6, position = position_dodge(.9)) + 
  geom_line(aes(y = metMean), size = 2.5, alpha = 0.5, color = "#343434") + 
  geom_point(aes( y = metMean), size = 7) + 
  geom_errorbar(aes(ymin = metMean-metsd, ymax = metMean+metsd), width = 6, position = position_dodge(.9)) +
  facet_grid(contraction ~ model) + 
  labs(x = "Torque [Nm]",
       y = "Energy Expenditure [J]"
       ) + 
  theme(
    strip.text.x = element_text(
      size = 30, color = "black", face = "bold"
    ),
    strip.text.y = element_text(
      size = 30, color = "black", face = "bold"
    ),
    axis.title = element_text(
      size = 34, face = "bold"
    ),
    axis.text.x = element_text(size = 30),
    axis.text.y = element_text(size= 30),
    panel.spacing = unit(2, "lines")
  ) + 
  scale_x_continuous(limits = c(10,90), breaks = c(20,40,60,80))

ggsave(file="../resultater/UnderEstimateKcal.jpeg", width=25, height=12, dpi = 1200)
```
